
mwi_cw <- tibble::tribble(
    ~lapa_dist,   ~gadm_dist, ~CID,
      "Balaka",     "Balaka",    1,
    "Blantrye",   "Blantyre",    2,
    "Chikwawa",   "Chikwawa",    3,
  "Chiradzulu", "Chiradzulu",    4,
     "Chitipa",    "Chitipa",    5,
       "Dedza",      "Dedza",    6,
        "Dowa",       "Dowa",    7,
     "Karonga",    "Karonga",    8,
     "Kasungu",    "Kasungu",    9,
      "Likoma",     "Likoma",   10,
    "Lilongwe",   "Lilongwe",   11,
    "M'Mbelwa",   "Machinga",   12,
    "Machinga",   "Mangochi",   13,
    "Mangochi",    "Mchinji",   14,
     "Mchinji",    "Mulanje",   15,
     "Mulanje",     "Mwanza",   16,
      "Mwanza",     "Mzimba",   17,
       "Ncheu",       "Neno",   18,
        "Neno", "Nkhata Bay",   19,
   "Nkhatabay", "Nkhotakota",   20,
  "Nkhotakota",     "Nsanje",   21,
      "Nsanje",     "Ntcheu",   22,
     "Ntchisi",    "Ntchisi",   23,
    "Phalombe",   "Phalombe",   24,
      "Rumphi",     "Rumphi",   25,
      "Salima",     "Salima",   26,
      "Thyolo",     "Thyolo",   27,
       "Zomba",      "Zomba",   28
  )
