
mwi_cw <- tibble::tribble(
    ~lapa_district,    ~district, ~CID,
          "Balaka",     "Balaka",    1,
        "Blantrye",   "Blantyre",    2,
        "Chikwawa",   "Chikwawa",    3,
      "Chiradzulo", "Chiradzulu",    4,
         "Chitipa",    "Chitipa",    5,
           "Dedza",      "Dedza",    6,
            "Dowa",       "Dowa",    7,
         "Karonga",    "Karonga",    8,
         "Kasungu",    "Kasungu",    9,
          "Likoma",     "Likoma",   10,
        "Lilongwe",   "Lilongwe",   11,
        "Machinga",   "Machinga",   12,
        "Mangochi",   "Mangochi",   13,
         "Mchinji",    "Mchinji",   14,
         "Mulanje",    "Mulanje",   15,
          "Mwanza",     "Mwanza",   16,
        "M'mbelwa",     "Mzimba",   17,
            "Neno",       "Neno",   18,
       "Nkhatabay", "Nkhata Bay",   19,
      "Nkhotakota", "Nkhotakota",   20,
          "Nsanje",     "Nsanje",   21,
          "Ntcheu",     "Ntcheu",   22,
         "Ntchisi",    "Ntchisi",   23,
        "Phalombe",   "Phalombe",   24,
          "Rumphi",     "Rumphi",   25,
          "Salima",     "Salima",   26,
          "Thyolo",     "Thyolo",   27,
           "Zomba",      "Zomba",   28
    )

